version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db-init
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db/mydb
      - USER_UUID=user-uuid-value
      - ADMIN_UUID=admin-uuid-value
      - APP_SECRET=app-secret-value
      - herokuJson=/app/config.json
      - FLASK_ENV=production
    volumes:
      - ./:/app
      - ./server.crt:/app/server.crt
      - ./server.key:/app/server.key
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 512M
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      # PostgreSQL performance tuning
      POSTGRES_SHARED_BUFFERS: 256MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 768MB
      POSTGRES_WORK_MEM: 16MB
      POSTGRES_MAINTENANCE_WORK_MEM: 64MB
      POSTGRES_MAX_CONNECTIONS: 100
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
    restart: unless-stopped
    ports:
      - "5432:5432"

  db-init:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db/mydb
    command: python init-db.py
    restart: on-failure

volumes:
  postgres_data:
